---
- name: Backup
  hosts: all
  become: true
  tasks:

    - name: Create the backup directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 'u=rw,g=,o='
      loop:
        - /srv/data/backup/gitll/previous
        - /srv/data/backup/gitll/latest

    - name: Create server backup
      containers.podman.podman_container_exec:
        name: gitlab-pod-server
        command: "gitlab-backup create"

    - name: Remove previous backup directory
      ansible.builtin.file:
        path: "/srv/data/backup/gitll/previous"
        state: absent

    - name: Copy latest backup directory to previous
      ansible.builtin.copy:
        remote_src: true
        src: "/srv/data/backup/gitll/latest/"
        dest: "/srv/data/backup/gitll/previous/"
        owner: root
        group: root
        mode: 'u=rw,g=,o='

    - name: Remove latest backup directory
      ansible.builtin.file:
        path: "/srv/data/backup/gitll/latest"
        state: absent

    - name: Create latest backup directory
      ansible.builtin.file:
        path: "/srv/data/backup/gitll/latest"
        state: directory
        owner: root
        group: root
        mode: 'u=rw,g=,o='

    - name: Get server data volume path
      community.docker.docker_volume_info:
        name: gitlab-pod-server-data
      register: result
      changed_when: false

    - name: Get backup files list
      ansible.builtin.find:
        paths: "{{ result.volume.Mountpoint }}/backups"
        patterns: '*_gitlab_backup.tar'
      register: result
      changed_when: false

#    - name: Debug
#      ansible.builtin.debug:
#        msg: "{{ (result.files | sort(attribute='mtime') | last).path }}"
#
#
#     - name: Debug
#       ansible.builtin.debug:
#         msg: "{{ result.files[0].path }}"
#

    - name: Copy the latest backup to latest directory
      ansible.builtin.copy:
        remote_src: true
        src: "{{ (result.files | sort(attribute='mtime') | last).path }}"
        dest: "/srv/data/backup/gitll/latest/"
        owner: root
        group: root
        mode: 'u=rw,g=,o='

    - name: Get server config volume path
      community.docker.docker_volume_info:
        name: gitlab-pod-server-config
      register: result
      changed_when: false

#    - name: Debug
#      ansible.builtin.debug:
#        var: result.volume.Mountpoint

    - name: Copy secrets
      ansible.builtin.copy:
        remote_src: true
        src: "{{ result.volume.Mountpoint }}/{{ item.name }}"
        dest: "/srv/data/backup/gitll/latest/{{ item.name }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      loop:
        - { name: 'gitlab-secrets.json', mode: 'u=rw,g=,o=' }
        - { name: 'ssh_host_ecdsa_key', mode: 'u=rw,g=,o=' }
        - { name: 'ssh_host_ecdsa_key.pub', mode: 'u=rw,g=r,o=r' }
        - { name: 'ssh_host_ed25519_key', mode: 'u=rw,g=,o=' }
        - { name: 'ssh_host_ed25519_key.pub', mode: 'u=rw,g=r,o=r' }
        - { name: 'ssh_host_rsa_key', mode: 'u=rw,g=,o=' }
        - { name: 'ssh_host_rsa_key.pub', mode: 'u=rw,g=r,o=r' }
